List<String> jobs = [
  "Electrical",
  "Painting",
  "Plumping",
  "Home Appliances",
  "Cleaning",
  "Home Shifting",
  "Furniture",
  "Bakery",
  "Clothing",
  "Tailoring",
  "Saloon",
  "General Service",
  "Groceries",
  "Decoration",
  "Rental",
  "Vehicle Service",
];
